### ISSUE TITLE
Un-needed event

### ISSUE THREAD

**Issue by Nexela** [Nebual/theyremadeoutofmeat#1]
script.on_event({defines.events.on_entity_died}, function (e)
    if e.entity.type == "unit" and e.entity.prototype.subgroup.name == "enemies" and e.entity.surface ~= nil then
        local count = math.min(50, math.max(1, math.floor(math.sqrt(e.entity.prototype.max_health/10))))
        local meat = e.entity.surface.spill_item_stack(e.entity.position, {name="raw-meat", count=count}, false)
    end
end)

Instead of having this in control you can add it as "loot" in the data prototype (with probabilities)

see https://mods.factorio.com/mods/Nexela/BiterBacon for examples if needed

**Comment by Nebual** [comment]
Ahh neat, I'd imagine that's a lot more efficient. Will do!

**Comment by Nebual** [comment]
I'm not certain if I like the 'auto pickup' that LuaEntityPrototype.loot forces, as now players inventories will inexplicably fill with meat... which is pretty funny.

Thanks!

**Comment by Nexela** [comment]
If there is not an option to disable mark as loot I will see about adding
one in .16 sometime
